### ISSUE TITLE
Carga de clases - Error de horario

### ISSUE THREAD

**Issue by KatuGT** [cristiandcode/Gimnasio#24]
![image](https://github.com/cristiandcode/Gimnasio/assets/38865485/0cc5c938-2006-4a92-bf67-1f7c9bf6ff25)
![image](https://github.com/cristiandcode/Gimnasio/assets/38865485/48e78afc-7537-4c7d-8501-78fe9e799f3e)
Cuando agregas horario que no son aceptados, deberia aparecer el error justo debajo de ese input

**Comment by KatuGT** [comment]
Corregido!
![image](https://github.com/user-attachments/assets/fe916179-e337-421c-9b26-4129010e92d0)

**Comment by cristiandcode** [comment]
Completado profe
